---
abstract: "Read and process an SNMP trap from Net-SNMP's snmptrapd"
author:
  - 'Ton Voon <ton.voon@opsera.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SNMP-Trapinfo
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: '0.05'
  Safe: '2.11'
version: '1.03'
